// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	consts "hello/constants"
)

func main() {
	h := server.Default(server.WithHostPorts(consts.RouterAddr))

	register(h)
	h.Spin()
}
