// Code generated by hertz generator.

package hello

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _hellomethodMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _newmethodMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _othermethodMw() []app.HandlerFunc {
	// your code...
	return nil
}
