// Code generated by Kitex v0.5.2. DO NOT EDIT.

package decrypt

import (
	"context"
	api "decrypt/kitex_gen/api"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

func serviceInfo() *kitex.ServiceInfo {
	return decryptServiceInfo
}

var decryptServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "decrypt"
	handlerType := (*api.Decrypt)(nil)
	methods := map[string]kitex.MethodInfo{
		"decrypt": kitex.NewMethodInfo(decryptHandler, newDecryptDecryptArgs, newDecryptDecryptResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "api",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.5.2",
		Extra:           extra,
	}
	return svcInfo
}

func decryptHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*api.DecryptDecryptArgs)
	realResult := result.(*api.DecryptDecryptResult)
	success, err := handler.(api.Decrypt).Decrypt(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newDecryptDecryptArgs() interface{} {
	return api.NewDecryptDecryptArgs()
}

func newDecryptDecryptResult() interface{} {
	return api.NewDecryptDecryptResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Decrypt(ctx context.Context, req *api.Request) (r *api.Response, err error) {
	var _args api.DecryptDecryptArgs
	_args.Req = req
	var _result api.DecryptDecryptResult
	if err = p.c.Call(ctx, "decrypt", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
