// Code generated by hertz generator.

package api

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _callMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _concatMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _encryptMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _decryptMw() []app.HandlerFunc {
	// your code...
	return nil
}
