// Code generated by Kitex v0.5.2. DO NOT EDIT.

package encrypt

import (
	"context"
	api "encrypt/kitex_gen/api"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

func serviceInfo() *kitex.ServiceInfo {
	return encryptServiceInfo
}

var encryptServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "encrypt"
	handlerType := (*api.Encrypt)(nil)
	methods := map[string]kitex.MethodInfo{
		"encrypt": kitex.NewMethodInfo(encryptHandler, newEncryptEncryptArgs, newEncryptEncryptResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "api",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.5.2",
		Extra:           extra,
	}
	return svcInfo
}

func encryptHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*api.EncryptEncryptArgs)
	realResult := result.(*api.EncryptEncryptResult)
	success, err := handler.(api.Encrypt).Encrypt(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newEncryptEncryptArgs() interface{} {
	return api.NewEncryptEncryptArgs()
}

func newEncryptEncryptResult() interface{} {
	return api.NewEncryptEncryptResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Encrypt(ctx context.Context, req *api.Request) (r *api.Response, err error) {
	var _args api.EncryptEncryptArgs
	_args.Req = req
	var _result api.EncryptEncryptResult
	if err = p.c.Call(ctx, "encrypt", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
