// Code generated by hertz generator.

package api

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"github.com/cloudwego/kitex/pkg/loadbalance"
	"log"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/cloudwego/kitex/client"
	"github.com/cloudwego/kitex/client/genericclient"
	"github.com/cloudwego/kitex/pkg/generic"
	etcd "github.com/kitex-contrib/registry-etcd"
)

// Call .
// @router /post [POST]
func Call(ctx context.Context, c *app.RequestContext) {
	//url to sendreq?
	var requestURL string = "http://example.com/life/client/11?vint64=1&items=item0,item1,item2"
	var IDLPATH string = "idl/hello.thrift"
	var jsonData map[string]interface{}

	//return data in bytes
	response := c.GetRawData()

	err := json.Unmarshal(response, &jsonData)

	if err != nil {
		fmt.Println("Error", err)
		c.String(consts.StatusBadRequest, "bad post request")
		return
	}

	fmt.Println(jsonData)

	responseFromRPC, err := makeThriftCall(IDLPATH, jsonData, requestURL, ctx)

	if err != nil {
		fmt.Println(err)
		c.String(consts.StatusBadRequest, "error in thrift call ")
		return
	}

	fmt.Println("Post request successful")

	c.JSON(consts.StatusOK, responseFromRPC)
}

func makeThriftCall(IDLPath string, jsonData map[string]interface{}, requestURL string, ctx context.Context) (interface{}, error) {
	p, err := generic.NewThriftFileProvider(IDLPath)
	if err != nil {
		fmt.Println("error creating thrift file provider")
		return 0, err
	}

	g, err := generic.JSONThriftGeneric(p)
	if err != nil {
		return 0, errors.New(("error creating thrift generic"))
	}

	r, err := etcd.NewEtcdResolver([]string{"127.0.0.1:2379"})
	if err != nil {
		log.Fatal(err)
	}

	cli, err := genericclient.NewClient("Call", g, client.WithResolver(r), client.WithLoadBalancer(loadbalance.NewWeightedRoundRobinBalancer()))

	if err != nil {
		return 0, errors.New(("invalid client name"))
	}

	// req, err := http.NewRequest(http.MethodGet, requestURL, bytes.NewBuffer(response))
	// req.Header.Set("token", "1")
	// if err != nil {
	// 	fmt.Println("error construting req")
	// 	return 0, err
	// }

	jsonString, _ := json.Marshal(jsonData)

	// customReq, err := generic.FromHTTPRequest(req)

	// if err != nil {
	// 	fmt.Println("error constructing xcustom req")
	// 	return 0, err
	// }

	// fmt.Println(customReq)

	resp, err := cli.GenericCall(ctx, "call", string(jsonString))

	if err != nil {
		fmt.Println("error making generic call")
		return 0, err
	}

	respString, ok := resp.(string)
	if !ok {
		fmt.Println("resp is not a string. Actual value:", resp)
		return nil, errors.New("resp is not a string")
	}

	fmt.Println("generic call successful:", respString)

	var respData map[string]interface{}
	err = json.Unmarshal([]byte(respString), &respData)
	if err != nil {
		fmt.Println("error unmarshalling response", err)
		return nil, err
	}

	fmt.Println("response:", respData["message"])

	return respData, nil
}
