// Code generated by Kitex v0.5.2. DO NOT EDIT.

package concat

import (
	api "concat/kitex_gen/api"
	"context"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

func serviceInfo() *kitex.ServiceInfo {
	return concatServiceInfo
}

var concatServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "concat"
	handlerType := (*api.Concat)(nil)
	methods := map[string]kitex.MethodInfo{
		"concat": kitex.NewMethodInfo(concatHandler, newConcatConcatArgs, newConcatConcatResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "api",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.5.2",
		Extra:           extra,
	}
	return svcInfo
}

func concatHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*api.ConcatConcatArgs)
	realResult := result.(*api.ConcatConcatResult)
	success, err := handler.(api.Concat).Concat(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newConcatConcatArgs() interface{} {
	return api.NewConcatConcatArgs()
}

func newConcatConcatResult() interface{} {
	return api.NewConcatConcatResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Concat(ctx context.Context, req *api.Request) (r *api.Response, err error) {
	var _args api.ConcatConcatArgs
	_args.Req = req
	var _result api.ConcatConcatResult
	if err = p.c.Call(ctx, "concat", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
